# Generated by Django 3.2.5 on 2021-07-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testanswers',
            name='status',
            field=models.CharField(max_length=5, verbose_name='Правильный/неправильный'),
        ),
    ]
