# Generated by Django 3.2.5 on 2021-07-30 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check_knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestions',
            name='question',
            field=models.TextField(default=None, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='testquestions',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='check_knowledge.test'),
        ),
        migrations.CreateModel(
            name='TestAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default=None, verbose_name='Ответ')),
                ('status', models.CharField(choices=[('right', 'Верный'), ('wrong', 'Неправильный')], default='wrong', max_length=5, verbose_name='Правильный/неправильный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='check_knowledge.testquestions')),
            ],
        ),
    ]
